### ISSUE TITLE
class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using wrong state class 'measurement' 

### ISSUE THREAD

**Issue by Vitus-TL** [Danielhiversen/home_assistant_tibber_data#76] opened 2023-10-25 13:49 UTC
Home Assistant 2023.10.5 Supervisor 2023.10.0 Operating System 11.0

WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.average_of_3_highest_hourly_consumption_xxxxxx (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' 
which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing';

WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.yearly_cost_xxxxxx (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible consider
ing device class ('monetary') it is using; expected None or one of 'total';

WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.monthly_consump
tion_compared_to_last_year_xxxxxx (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement
' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 

WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.monthly_production_profit_xxxxxx (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total';

**Comment by Danielhiversen** [comment] 2023-10-31 15:51
Duplicate of https://github.com/Danielhiversen/home_assistant_tibber_data/issues/61

**Closed by Danielhiversen** 2023-10-31 15:51 UTC
