### ISSUE TITLE
Mismatch between sensor state class and device class

### ISSUE THREAD

**Issue by frli4797** [Danielhiversen/home_assistant_tibber_data#61] opened 2023-03-27 15:37 UTC
`Entity sensor.yearly_consumption_xxx (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.`

**Comment by tedenda** [comment] 2023-06-17 15:28
Same issue as #56

**Comment by oywino** [comment] 2023-08-16 17:39
I guess this is the same issue :

```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:506
Integration: Sensor (documentation, issues)
First occurred: 7:25:16 PM (6 occurrences)
Last logged: 7:25:16 PM

Entity sensor.daily_cost_with_subsidy_middelthunsgate_17c (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.yearly_cost_middelthunsgate_17c (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.yearly_consumption_middelthunsgate_17c (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.monthly_consumption_compared_to_last_year_middelthunsgate_17c (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.monthly_cost_with_subsidy_middelthunsgate_17c (<class 'custom_components.tibber_data.sensor.TibberDataSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Comment by Danielhiversen** [comment] 2024-04-09 18:49
Duplicate of https://github.com/Danielhiversen/home_assistant_tibber_data/issues/56

**Closed by Danielhiversen** 2024-04-09 18:49 UTC
